fastprint/urls.py
from django.contrib import admin
from django.urls import path, include #mengimport modul include untuk mengambil url patterns dari direktori lain
from fastprint_app import urls as dashboard #mengimport url patterns dari direktori app dan mengannti nama nya dengan alias 'dashboard'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(dashboard)), #url '' (kosong) yang berfungsi ketika program di run maka ia adalah path url pertama yang akan dieksekusi
]

fastprint_app/urls.py
from django.urls import path, include #mengimport library django.urls untuk pattern url di app
from . import views #menginisiasi file views.py

app_name = 'app' #membuat app name untuk urls app agar lebih mudah dikenali
urlpatterns=[
    path('get_api/', views.get_api, name='get_api'), #patterns 'get_api' yang akan mengembalikan data dari api berupa json
    path('create_kategori/', views.kategoriAPI, name='add_kategori'), # path url untuk menambahkan data kategori
    path('create_status/', views.statusAPI, name='add_status'), # path url untuk menambahkan data kategori
    
    path('', views.produk, name='admin_produk'),
    path('tambah-produk/', views.tambah, name='tambah_produk'),
    path('ubah-produk/<str:id>/', views.ubah, name='ubah_produk'), # Path url untuk merubah data dengan parameter id
    path('hapus-produk/<str:id>/', views.delete, name='hapus_produk'), # Path url untuk menghapus data dengan parameter id
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Junior Programmer Fast Print Indonesia</title>
    <!-- CDN Boostrap, JS, Popper.js, JQUERY dan sweetalert dari web https://cdnjs.com/libraries/bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <style>
        .swal2-confirm {
            margin-right: 10px;
        }
    </style>
</head>
<body>
     {% block main %} <!-- ini digunakan agar file html yang lain tinggal extend file ini saja -->
    {% endblock %}
    {% block scripts %}
    {% endblock %}
</body>
</html>

templates/create.html
{% extends 'base.html' %}
{% block main %}
    <div class="card-body">
        <h5 class="text-center mb-5">{% if not edit %} Tambah {% else %} Ubah {% endif %} Data Produk</h5>
        <form method="post" class="text-center" 
        {% if not edit %} action="{% url 'app:tambah_produk' %}" {% else %} action="{% url 'app:ubah_produk' data.id_produk %}" {% endif %}>
            {% csrf_token %}
            <div class="form-row">
                <div class="col-4">
                    <div class="form-group">
                        <label for="id">Masukan ID Produk</label>
                        <input type="number" name="id" class="form-control" {% if edit %} disabled {% endif %} value="{{data.id_produk}}">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="id">Masukan Nama Produk</label>
                        <input type="text" name="nama" class="form-control" required value="{{data.nama_produk}}">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="id">Masukan Harga Produk</label>
                        <input type="number" name="harga" class="form-control" value="{{data.harga}}">
                    </div>
                </div>
            </div>
            <div class="form-row justify-content-center">
                <div class="col-4">
                    <div class="form-group">
                        <label for="id">Pilih Kategori Produk</label>
                        <select name="kategori" class="form-control">
                            {% if not edit %}
                                <option value="" {% if not edit %} selected {% endif %}>---PILIH---</option>
                            {% else %}
                                <option value="{{data.kategori.id_kategori}}">{{data.kategori.nama_kategori}}</option>
                            {% endif %}
                            {% for x in kategori %}
                                <option value="{{x.id_kategori}}">{{x.nama_kategori}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="id">Pilih Status Produk</label>
                        <select name="status" class="form-control">
                            {% if not edit %}
                                <option value="" {% if not edit %} selected {% endif %}>---PILIH---</option>
                            {% else %}
                                <option value="{{data.status.id_status}}">{{data.status.nama_status}}</option>
                            {% endif %}

                            {% for x in status %}
                                <option value="{{x.id_status}}">{{x.nama_status}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            
            <a type="button" class="btn btn-danger" href="{% url 'app:admin_produk' %}">Cancel</a>
            <button type="submit" class="btn btn-success">{% if not edit %} Create {% else %} Update {% endif %}</button>
        </form>
    </div>
{% endblock %}

templates/dashboard.html
 {% extends 'base.html' %} <!-- mengekstend base.html -->
 {% load custom_tags %}
 {% block main %}
    <div class="card-body">
        <h4>Daftar Produk</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID Produk</th>
                    <th scope="col">Nama Produk</th>
                    <th scope="col">Harga</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Status</th>
                    <th scope="col">Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% for x in data %}
                <tr>
                    <td>{{ x.id_produk }}</td>
                    <td>{{ x.nama_produk }}</td>
                    <td>{{ x.harga|currency }}</td>
                    <td>{{ x.kategori.nama_kategori }}</td>
                    <td>{{ x.status.nama_status }}</td>
                    <td>
                        <a type="button" class="btn btn-warning" href="{% url 'app:ubah_produk' x.id_produk %}">Update</a>
                        <button class="btn btn-danger text-white" data-url="{% url 'app:hapus_produk' x.id_produk %}"
                        data-back="{% url 'app:admin_produk' %}"
                        onclick="delete_data(this, '{{x.nama_produk}}')">Delete</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <a type="button" class="btn btn-success" href="{% url 'app:tambah_produk' %}" style="margin-right: 5px;">Create</a>
            <form action="{% url 'app:get_api' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Get API Data</button>
            </form>
        </div>  
    </div>
 {% endblock %}
 {% block scripts %}
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
 <script>
     function delete_data(e, categoryName) {
        Swal.fire({
            title: 'Hapus Produk',
            text: `Apakah Kamu Ingin menghapus "${categoryName}"?`,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes',
            cancelButtonText: 'No',
            buttonsStyling: false,
            customClass: {
                confirmButton: 'btn btn-danger',
                cancelButton: 'btn btn-primary',
            },
        }).then(function (result) {
            if (result.isConfirmed) {
                $.ajax({
                    url: $(e).attr('data-url'),
                    data: {},
                    dataType: "json",
                    timeout: 10000,
                    success: function(response){
                        if(response.message == 'error'){
                            Swal.fire({
                                text: data.error_message,
                                icon: "error",
                                buttonsStyling: false,
                                confirmButtonText: "Ok, mengerti!",
                                customClass: { confirmButton: "btn btn-primary" }
                            });
                        }else{
                            Swal.fire({
                                text: "Data anda berhasil dihapus!",
                                icon: "success",
                                buttonsStyling: false,
                                confirmButtonText: "Ok, mengerti!",
                                customClass: { confirmButton: "btn btn-primary" }
                            }).then(function (result) {
                                if (result.isConfirmed) {
                                    window.location.reload(true);
                                }
                            });
                        } 
                    },
                    error: function (response) {
                        console.log(response);
                        Swal.fire('Arsip data gagal dilakukan!', '', 'error');
                        setTimeout(function(){ 
                            window.location.href = $(e).attr('data-back');
                        }, 2000);
                    }
                });
            }
        });
    }
 </script>
 {% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Junior Programmer</title>
</head>
<body>
    <form action="{% url 'app:get_api' %}" method="post">
        {% csrf_token %}
        <button type="submit">Submit data post</button>
    </form>
</body>
</html>